name: Release new fatJar

on:
  release:
    types: [published]

jobs:
  releases:
    name: Build fatJar using pottery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Pottery build fatJar
        env:
          POTTERY_VERSION: 0.0.1
        run: ./src/main/sh/pottery.sh package
      - name: Upload Jar Artifact
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/pottery-${{ github.event.release.tag_name }}-fat.jar application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate md5 checksum
        run: md5sum < target/pottery-${{ github.event.release.tag_name }}-fat.jar | awk '{print $1}' > target/pottery-${{ github.event.release.tag_name }}-fat.jar.md5

      - name: Upload md5 checksum
        uses: JasonEtco/upload-to-release@master
        with:
          args: target/pottery-${{ github.event.release.tag_name }}-fat.jar.md5 text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload pottery.sh
        uses: JasonEtco/upload-to-release@master
        with:
          args: src/main/sh/pottery.sh text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

